name: weather
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.6.0
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/MaterialIcons-Regular.otf
    - assets/fonts/Roboto-VariableFont_wdth,wght.ttf
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf
